services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Enable auto topic creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    command:
      - bash
      - -c
      - |
        /etc/confluent/docker/run &
        echo "Waiting for Kafka to start..."
        cub kafka-ready -b localhost:9092 1 30
        kafka-topics --create --if-not-exists \
          --topic taxi_trips \
          --bootstrap-server localhost:9092 \
          --partitions 3 \
          --replication-factor 1
        wait

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./data:/app/data
    command: python producer/producer.py

  spark:
    image: bitnami/spark:3.4.2
    container_name: spark
    depends_on:
      - kafka
    volumes:
      - ./spark:/app
      - ~/.ivy2:/root/.ivy2
    command: >
      spark-submit
        --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.2
        /app/stream_job_console.py
